let imageInfo = document.getElementById('imageDropdown');
let infoTitle = document.getElementById('imageTitle');
let infoDescription = document.getElementById('imageDescription');
if (imageInfo.value == 'ngc1850-blue') {
    infoTitle.innerHTML = 'NGC 1850';
    infoDescription.innerHTML = 'This 100 million-year-old globular cluster is located in the Large Magellanic Cloud, a satellite galaxy of the Milky Way and a birthplace for billions of stars. The cluster is approximately 160,000 light-years away in the constellation Dorado. Typical of globular clusters, it is a spherical collection of densely packed stars held together by mutual gravitational attraction. Unlike most globular clusters, however, the stars of NGC 1850 are relatively young. Globular clusters with young stars such as NGC 1850 are not present in our own Milky Way galaxy. Astrophysicists theorize that when the first generation of stars in NGC 1850 was born, the stars ejected matter like dust and gas into the surrounding cosmos.  The density of the newly formed star cluster was so high that this ejected matter could not escape the cluster’s gravitational pull, causing it to stay nearby. The intense gravity of the cluster also pulled in hydrogen and helium gas from its surroundings. These two sources of gas combined to form a second generation of stars, increasing the density and size of this globular cluster.';
} else if (imageInfo.value == 'acos295') {
    infoTitle.innerHTML = 'ACO S 295';
    infoDescription.innerHTML = 'This packed image taken with the NASA/ESA Hubble Space Telescope showcases the galaxy cluster ACO S 295, as well as a jostling crowd of background galaxies and foreground stars. Galaxies of all shapes and sizes populate this image, ranging from stately spirals to fuzzy ellipticals. This galactic menagerie boasts a range of orientations and sizes, with spiral galaxies such as the one at the center of this image appearing almost face on, and some edge-on spiral galaxies visible only as thin slivers of light. The galaxy cluster dominates the center of this image, both visually and physically. The cluster’s huge mass has gravitationally lensed the light from background galaxies, distorting and smearing their shapes. In addition to providing astronomers with a natural magnifying glass with which to study distant galaxies, gravitational lensing has subtly framed the center of this image, producing a visually striking scene.';
}
imageInfo.addEventListener('change', (event) => {
    if (imageInfo.value == 'ngc1850-blue') {
        infoTitle.innerHTML = 'NGC 1850';
        infoDescription.innerHTML = 'This 100 million-year-old globular cluster is located in the Large Magellanic Cloud, a satellite galaxy of the Milky Way and a birthplace for billions of stars. The cluster is approximately 160,000 light-years away in the constellation Dorado. Typical of globular clusters, it is a spherical collection of densely packed stars held together by mutual gravitational attraction. Unlike most globular clusters, however, the stars of NGC 1850 are relatively young. Globular clusters with young stars such as NGC 1850 are not present in our own Milky Way galaxy. Astrophysicists theorize that when the first generation of stars in NGC 1850 was born, the stars ejected matter like dust and gas into the surrounding cosmos.  The density of the newly formed star cluster was so high that this ejected matter could not escape the cluster’s gravitational pull, causing it to stay nearby. The intense gravity of the cluster also pulled in hydrogen and helium gas from its surroundings. These two sources of gas combined to form a second generation of stars, increasing the density and size of this globular cluster.';
    } else if (imageInfo.value == 'acos295') {
        infoTitle.innerHTML = 'ACO S 295';
        infoDescription.innerHTML = 'This packed image taken with the NASA/ESA Hubble Space Telescope showcases the galaxy cluster ACO S 295, as well as a jostling crowd of background galaxies and foreground stars. Galaxies of all shapes and sizes populate this image, ranging from stately spirals to fuzzy ellipticals. This galactic menagerie boasts a range of orientations and sizes, with spiral galaxies such as the one at the center of this image appearing almost face on, and some edge-on spiral galaxies visible only as thin slivers of light. The galaxy cluster dominates the center of this image, both visually and physically. The cluster’s huge mass has gravitationally lensed the light from background galaxies, distorting and smearing their shapes. In addition to providing astronomers with a natural magnifying glass with which to study distant galaxies, gravitational lensing has subtly framed the center of this image, producing a visually striking scene.';
    }
});