let imageInfo = document.getElementById('imageDropdown');
let infoTitle = document.getElementById('imageTitle');
let infoDescription = document.getElementById('imageDescription');
if (imageInfo.value == 'ngc1850-blue') {
    infoTitle.innerHTML = 'NGC 1850';
    infoDescription.innerHTML = 'This 100 million-year-old globular cluster is located in the Large Magellanic Cloud, a satellite galaxy of the Milky Way and a birthplace for billions of stars. The cluster is approximately 160,000 light-years away in the constellation Dorado. Typical of globular clusters, it is a spherical collection of densely packed stars held together by mutual gravitational attraction. Unlike most globular clusters, however, the stars of NGC 1850 are relatively young. Globular clusters with young stars such as NGC 1850 are not present in our own Milky Way galaxy. Astrophysicists theorize that when the first generation of stars in NGC 1850 was born, the stars ejected matter like dust and gas into the surrounding cosmos.  The density of the newly formed star cluster was so high that this ejected matter could not escape the cluster’s gravitational pull, causing it to stay nearby. The intense gravity of the cluster also pulled in hydrogen and helium gas from its surroundings. These two sources of gas combined to form a second generation of stars, increasing the density and size of this globular cluster.';
} else if (imageInfo.value == 'acos295') {
    infoTitle.innerHTML = 'ACO S 295';
    infoDescription.innerHTML = 'This galaxy cluster is located in the constellation of Horologium, approximately 3.5 billion light-years away. It is part of the Abell catalog of galaxy clusters, which contains over 4,000 clusters. Galaxy clusters are the largest gravitationally bound structures in the universe, containing hundreds or thousands of galaxies. The galaxies in a cluster are held together by their mutual gravitational attraction. The cluster is composed of elliptical and spiral galaxies, as well as irregular galaxies. The elliptical galaxies are the most massive and luminous, while the spiral galaxies are less massive and have more gas and dust. The irregular galaxies are the smallest and least massive, with irregular shapes and low luminosity. Galaxy clusters like ACO S 295 are important for studying the large-scale structure of the universe and the evolution of galaxies over time.';
}
imageInfo.addEventListener('change', (event) => {
    if (imageInfo.value == 'ngc1850-blue') {
        infoTitle.innerHTML = 'NGC 1850';
        infoDescription.innerHTML = 'This 100 million-year-old globular cluster is located in the Large Magellanic Cloud, a satellite galaxy of the Milky Way and a birthplace for billions of stars. The cluster is approximately 160,000 light-years away in the constellation Dorado. Typical of globular clusters, it is a spherical collection of densely packed stars held together by mutual gravitational attraction. Unlike most globular clusters, however, the stars of NGC 1850 are relatively young. Globular clusters with young stars such as NGC 1850 are not present in our own Milky Way galaxy. Astrophysicists theorize that when the first generation of stars in NGC 1850 was born, the stars ejected matter like dust and gas into the surrounding cosmos.  The density of the newly formed star cluster was so high that this ejected matter could not escape the cluster’s gravitational pull, causing it to stay nearby. The intense gravity of the cluster also pulled in hydrogen and helium gas from its surroundings. These two sources of gas combined to form a second generation of stars, increasing the density and size of this globular cluster.';
    } else if (imageInfo.value == 'acos295') {
        infoTitle.innerHTML = 'ACO S 295';
        infoDescription.innerHTML = 'This galaxy cluster is located in the constellation of Horologium, approximately 3.5 billion light-years away. It is part of the Abell catalog of galaxy clusters, which contains over 4,000 clusters. Galaxy clusters are the largest gravitationally bound structures in the universe, containing hundreds or thousands of galaxies. The galaxies in a cluster are held together by their mutual gravitational attraction. The cluster is composed of elliptical and spiral galaxies, as well as irregular galaxies. The elliptical galaxies are the most massive and luminous, while the spiral galaxies are less massive and have more gas and dust. The irregular galaxies are the smallest and least massive, with irregular shapes and low luminosity. Galaxy clusters like ACO S 295 are important for studying the large-scale structure of the universe and the evolution of galaxies over time.';
    }
});